### ISSUE TITLE
python 3 items

### ISSUE THREAD

**Issue by jonnymaserati** [ukuleleplayer/pureples#11]
If being run on Python 3 then `iteritems` needs to be replaced with `items` in es_hyperneat.py and visualize.py (and probably others).

Is it possible to add a version checker and run the appropriate line of code based on that result?

**Comment by ukuleleplayer** [comment]
You are more than welcome to change it to Python 3 compatible code or use a version checker -  I'm not sure if anybody is running Python 2 anymore for these kind of tasks.
Anyway, I'll approve the PR quickly if you make one :)
