### ISSUE TITLE
Slow performance when running es-HyperNEAT in parallel

### ISSUE THREAD

**Issue by PlayerCFM** [ukuleleplayer/pureples#15]
Hello.
I've been trying to run a script in parallel reusing some code implementation that I already have on vanilla NEAT and which got using the instructions in the NEAT documentation.
A summary of the code I am using is as follows:

```

### Definition of the input and output nodes for the substrate
sub = Substrate(input_coordinates, output_coordinates)

params = { ### Params definition }

### Reading and standarizing data.
XInput, YOutput = GetData()

def eval_genome(genome, config):
    cppn = neat.nn.FeedForwardNetwork.create(genome, config)
    network = ESNetwork(sub, cppn, params)
    net = network.create_phenotype_network()
    fitness=0.0
    for xi, yo in zip(XInput, YOutput):
        for k in range(network.activations):
            o = net.activate(xi)
        error = CalculateError(yo, o)
        fitness = 1 - error

    return fitness   

def run(gens):
    config = neat.config.Config(neat.genome.DefaultGenome, neat.reproduction.DefaultReproduction,
                            neat.species.DefaultSpeciesSet, neat.stagnation.DefaultStagnation,
                            'config-file')

    pop = neat.population.Population(config)
    stats = neat.statistics.StatisticsReporter()
    pop.add_reporter(stats)
    pop.add_reporter(neat.reporting.StdOutReporter(True))

    pe = neat.ParallelEvaluator(multiprocessing.cpu_count()-1, eval_genome)
    winner = pop.run(pe.evaluate, 150)
    return winner, stats

if __name__ == '__main__':
    winner = run(300)[0]
```

When the script is run using a population of 2, the first generation ends but the second generation seems not to end.
When the population is larger (I have run it with 50, 100 and 150 individuals) not even the first generation ends.

Am I making a mistake in the implementation?
If you need more information regarding the code used, please let me know.

**Comment by aacoimbra** [comment]
I believe you are choosing a high value for the `max_depth` parameter.  This will significantly slow down the execution time of the `create_phenotype_network` function from the  `ESNetwork` object.

Increasing this value from 4 to 5 will slow down `create_phenotype_network` execution time from 684 to 1852 seconds for 40 genomes in the first generation of my project. And the performance will only get worse as the network gets more complex in the second generation and beyond.
