### ISSUE TITLE
Missing list() in es_hyperneat.py / unsupported operand type(s) for +: 'range' and 'range'

### ISSUE THREAD

**Issue by DaKnick** [ukuleleplayer/pureples#19]
Hi,
I think in **es_hyperneat.py** on line 30/31 the ranges for the input- and output_nodes should be transformed to a list with list().

Otherwise  _return neat.nn.RecurrentNetwork(input_nodes, output_nodes, node_evals)_ throws an error:
_unsupported operand type(s) for +: 'range' and 'range'_

Without that change skripts like **es_hyperneat_xor_large.py** do not work.

The same problem seems to appear in **hyperneat.py**

**Comment by LPioL** [comment]
I have the same problem.

**Comment by ukuleleplayer** [comment]
Thanks for bringing this up.
It's fixed now - due to some changes in the underlying NEAT framework
