### ISSUE TITLE
LSTM Cells

### ISSUE THREAD

**Issue by illion20** [ukuleleplayer/pureples#2]
Thanks for developing the library.

I was wondering if you ever thought of replacing the neuron cells with LSTM cells?
How hard would that be? The idea that an evolving neural network also can remember is fascinating.

**Comment by ukuleleplayer** [comment]
Hi! 
Glad you like the library.

We've actually never thought about using LSTM cells when we first created the library, but it sure sounds interesting. Unfortunately, we haven't got the time right now, but you are more than welcome to fork the library or make a pull request.
Cheers.
