### ISSUE TITLE
Connection's __eq__ does not return a boolean in es_hyperneat.py.

### ISSUE THREAD

**Issue by yamatakeru** [ukuleleplayer/pureples#21]
Hi.

Connection's `__eq__` is expected to return a boolean, but it returns a tuple `(float, float, float, bool, float, float, float)`.
However, the library seems to be working correctly at first glance.

Tentatively, I will create a PR.

**Comment by ukuleleplayer** [comment]
This should be working now, righty? 🔢

**Comment by yamatakeru** [comment]
I probably think it's working correctly.
