### ISSUE TITLE
Question about inference with evolved ANN

### ISSUE THREAD

**Issue by pablogranolabar** [ukuleleplayer/pureples#23]
Hi @ukuleleplayer,

I've been working on a PUREPLES-based project with your gym runner but I can't find any resources on inference with an evolved ANN? It looks like the phenotype gets pickled and model saved whenever the reward in +1., but what type of model format is that in and how to deploy for inference tasks?

What I want to do is implement an additional loop whenever a +1. reward is found, to test it n more times to see if it has generalized to other examples.

And does it make sense to restart an episode on each of those saved pickles for subsequent runs?

TIA!

**Comment by ukuleleplayer** [comment]
Hi @pablogranolabar,

I'm a bit unsure what you're trying to achieve - could you maybe provide a small sample code and specify your issue?
It's true that in the examples given, we're pickling some stuff. First off, this is voluntary and only done to be able to load e.g. the CPPN again and query various connections if needed. Or do you mean somewhere else than in the PUREPLES code?

Cheers,
Adrian

**Comment by pablogranolabar** [comment]
Hi Adrian!

So for example, once I've trained the large scale ANN in the XOR experiment, is this the preferred route for inference after unpickling the most recent checkpoint?

```
CPPN = neat.nn.FeedForwardNetwork.create(WINNER, CONFIG)
```

I am just trying to figure out the optimal method of running the evolved ANN after training has completed.
