### ISSUE TITLE
Question about hyperparameter tuning / memory consumption

### ISSUE THREAD

**Issue by pablogranolabar** [ukuleleplayer/pureples#24]
Hi again @ukuleleplayer 

I've got a collection of flat binary inputs of ```self.observation_space = spaces.Box(low=0., high=1., shape=(163840,))``` which by usual standards in Gym is not that large I don't think; however when evolving even the smallest parameter ANN, I'm getting OOM within seconds.

Do you have any thoughts on hyperparameter tuning with PUREPLES as relates to memory consumption? I get OOM even with a 64GB instance using this observation space.

TIA

**Comment by ukuleleplayer** [comment]
Hi,

That sounds like something is off in the code somewhere - if you configure the smallest possible ES network, well, then your bottleneck in memory consumption should definitely not be there.. I can't say be sure what's happening, but maybe look elsewhere than your parameter tuning. Check first whether it is even possible to run in a normal NEAT setup.

Cheers.
