### ISSUE TITLE
Multiple activation function support for ES-HyperNEAT?

### ISSUE THREAD

**Issue by pablogranolabar** [ukuleleplayer/pureples#25]
Hi @ukuleleplayer 

I've noticed that all of the examples use sigmoid activation functions for ES-HyperNEAT; is the use of multiple activation function at the per-neuron level possible with PUREPLES?

Or any activation function other than sigmoid for ES-HyperNEAT?

TIA

**Comment by ukuleleplayer** [comment]
Hi @pablogranolabar,

The underlying activations are handled by the NEAT-Python library - I refer to their documentation in regards to such: https://neat-python.readthedocs.io/en/latest/

Cheers
