### ISSUE TITLE
network.create_phenotype_network() executing for more than 30 minutes when input and output sizes are (49360,) and (1024,) respectively

### ISSUE THREAD

**Issue by Abdul-Wahab-mc** [ukuleleplayer/pureples#26]
I have been trying to use ES-Hyperneat on a custom environment. The size of input to ES-Network is (49360,) and for output is (1024,).
The "net = network.create_phenotype_network()" method is sometimes taking more than 30 minutes to execute for a single genome. 
Does it mean that the larger the size of input and output of network the more time it will take to create network? 

Is there any solution for this?

**Comment by ukuleleplayer** [comment]
That's definitely true, yes. The larger input/output, the more time it takes to create the network (exploring different pathways between these nodes combined with the pruning and extraction).
I would love to give it a go implementing this in e.g. Pytorch to allow optimized parallelization, but alas I haven't got the time. You're more than welcome to give it a shot!
