### ISSUE TITLE
The relationship between ESNetwork.activations and max_depth

### ISSUE THREAD

**Issue by lester1027** [ukuleleplayer/pureples#27]
Could anyone please explain the following line of code in es_hyperneat.py?

```
        # Number of layers in the network.
        self.activations = 2 ** params["max_depth"] + 1
```

Thank you very much.

**Comment by ukuleleplayer** [comment]
Take a look at: https://github.com/ukuleleplayer/pureples/blob/312f6c7c6f6dc8352365fd6543725cc6b935a1f6/pureples/experiments/xor/es_hyperneat_xor.py#L66
It is, as stated in the comment, the number of layers in the network - thus the need for activating the network self.activations number of times.
