### ISSUE TITLE
Installed but ....

### ISSUE THREAD

**Issue by lonnietc** [ukuleleplayer/pureples#29]
Hello,

I am testing out HyperNEAT_ES on Windows with your Pureples and have been able to install it from what I can tell, but am not sure how to run any of the experiments.

Can you please elaborate more on this?
Thanks

**Comment by ukuleleplayer** [comment]
Hi,

There are several experiments. All have files for running NEAT, HyperNEAT, HyperNEAT_ES or all above. It's simply running the python script with, yeah, python. The configuration is inside the respective files and the files inside the specific folder in which you're running.

What are you specifically in doubt about?

Cheers
