### ISSUE TITLE
Pruning extraction

### ISSUE THREAD

**Issue by Matthew-Prinold** [ukuleleplayer/pureples#7]
the conditional statement
 self.variance(c) > self.variance_threshold 
in the pruning extraction method of ESNetwork class needs a continue inserting on the line  after 
self.pruning_extraction(coord, c, outgoing)
otherwise it will continue on with the variables d_left, d_right, d_top and d_bottom all assigned as None resulting in TypeError: Unorderable types: NoneType() < NoneType()

**Comment by ukuleleplayer** [comment]
Thanks for noticing, this is totally correct - fixed it by moving the code below into the else statement, which is how it should look.
This is the pseudocode: 
![image](https://user-images.githubusercontent.com/6057043/54547535-3559ff00-49a6-11e9-8af5-dcbdab3f0202.png)
and it looks like that now. 

Cheers!
